/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;

import br.unirio.pcs.suta.CatalogoObra;
import br.unirio.pcs.suta.Obra;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import lombok.*;

/**
 *
 * @author Lucas
 */
public class CatalogoTela extends javax.swing.JFrame {
    
    @Getter
    private List<Obra> obras;
    
    /**
     * Creates new form Catalogo
     */
    public CatalogoTela() {
        
        initComponents();
        this.listObra();
        //this.renderDetailsOnClick();
    }

    public void listObra() {
        
        Obra ob = new Obra();
        this.obras = ob.deletarObra();
        DefaultTableModel model = (DefaultTableModel) catalogoTabela.getModel();

        for (int i = 0; i < obras.size(); i++) {

            Object rowData[] = new Object[3];
            rowData[0] = obras.get(i).getNome();
            rowData[1] = obras.get(i).getAutor();
            rowData[2] = obras.get(i).getEditora();
            model.addRow(rowData);
        }
    }

//    public void renderDetailsOnClick() {
//        final CatalogoTela athis = this;
//
//        this.catalogoTabela.addMouseListener(new MouseAdapter() {
//            public void mouseClicked(MouseEvent e) {
//                int row = catalogoTabela.getSelectedRow();
//                Obra obra = athis.deletar.get(row);
//                
//                if (e.getClickCount() == 2) {
//                    new HomeController().renderRestaurantDetails(athis, restaurante);
//                }
//            }
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        catalogoPane = new javax.swing.JScrollPane();
        catalogoTabela = new javax.swing.JTable();
        catalogoSugerirObras = new javax.swing.JButton();
        catalogoVoltar = new javax.swing.JButton();
        catalogoDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        catalogoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livro", "Autor", "Editora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catalogoPane.setViewportView(catalogoTabela);
        if (catalogoTabela.getColumnModel().getColumnCount() > 0) {
            catalogoTabela.getColumnModel().getColumn(0).setResizable(false);
            catalogoTabela.getColumnModel().getColumn(1).setResizable(false);
            catalogoTabela.getColumnModel().getColumn(2).setResizable(false);
        }

        catalogoSugerirObras.setText("Sugerir Obras para adição no catálogo");
        catalogoSugerirObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCatalogoSugerirObrasActionPerformed(evt);
            }
        });

        catalogoVoltar.setText("Voltar a Tela Inicial");
        catalogoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCatalogoVoltarActionPerformed(evt);
            }
        });

        catalogoDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        catalogoDescricao.setText("Catálogo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogoSugerirObras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(catalogoVoltar)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(catalogoDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(catalogoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(catalogoDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(catalogoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catalogoSugerirObras)
                    .addComponent(catalogoVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCatalogoSugerirObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCatalogoSugerirObrasActionPerformed
        MsgSugerirLivroTela msgSugestao = new MsgSugerirLivroTela();
        this.dispose();
        msgSugestao.setVisible(true);
    }//GEN-LAST:event_botaoCatalogoSugerirObrasActionPerformed

    private void botaoCatalogoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCatalogoVoltarActionPerformed
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoCatalogoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoTela().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel catalogoDescricao;
    private javax.swing.JScrollPane catalogoPane;
    private javax.swing.JButton catalogoSugerirObras;
    private javax.swing.JTable catalogoTabela;
    private javax.swing.JButton catalogoVoltar;
    // End of variables declaration//GEN-END:variables
}
