/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;
import br.unirio.pcs.suta.GeraBoleto;

/**
 *
 * @author Lucas
 */
public class FormEnderecoTela extends javax.swing.JFrame {

    /**
     * Creates new form FormEndereco
     */
    public FormEnderecoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formEntregaDescrTitulo = new javax.swing.JLabel();
        formEntregaDescrSubTitulo = new javax.swing.JLabel();
        formEntregaFieldNome = new javax.swing.JTextField();
        formEntregaFieldCEP = new javax.swing.JTextField();
        formEntregaFieldEndereco = new javax.swing.JTextField();
        formEntregaFieldNumero = new javax.swing.JTextField();
        formEntregaFieldComplemento = new javax.swing.JTextField();
        formEntregaFieldBairro = new javax.swing.JTextField();
        formEntregaFieldCidade = new javax.swing.JTextField();
        formEntregaFieldCPF = new javax.swing.JTextField();
        formEntregaDescrNome = new javax.swing.JLabel();
        formEntregaDescrCompl = new javax.swing.JLabel();
        formEntregaDescrCEP = new javax.swing.JLabel();
        formEntregaDescrBairro = new javax.swing.JLabel();
        formEntregaDescrEndereco = new javax.swing.JLabel();
        formEntregaDescrCidade = new javax.swing.JLabel();
        formEntregaDescrNumero = new javax.swing.JLabel();
        formEntregaDescrCPF = new javax.swing.JLabel();
        formEntregaVoltar = new javax.swing.JButton();
        formEntregaProsseguir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formEntregaDescrTitulo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        formEntregaDescrTitulo.setText("Formulário de Entrega");

        formEntregaDescrSubTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formEntregaDescrSubTitulo.setText("Insira os dados de entrega para finalizar o pedido e prosseguir para a tela de pagamento:");

        formEntregaDescrNome.setText("Nome do destinatário");

        formEntregaDescrCompl.setText("Complemento");

        formEntregaDescrCEP.setText("CEP");

        formEntregaDescrBairro.setText("Bairro");

        formEntregaDescrEndereco.setText("Endereço");

        formEntregaDescrCidade.setText("Cidade");

        formEntregaDescrNumero.setText("Número");

        formEntregaDescrCPF.setText("CPF");

        formEntregaVoltar.setText("Voltar para tela de pedido");
        formEntregaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFormEntregaVoltarActionPerformed(evt);
            }
        });

        formEntregaProsseguir.setText("Prosseguir para pagamento");
        formEntregaProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFormEntregaProsseguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formEntregaDescrNome)
                        .addComponent(formEntregaDescrCEP)
                        .addComponent(formEntregaDescrEndereco)
                        .addComponent(formEntregaDescrNumero)
                        .addComponent(formEntregaFieldCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(formEntregaFieldNumero)
                        .addComponent(formEntregaFieldNome))
                    .addComponent(formEntregaFieldEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(formEntregaDescrCompl)
                    .addComponent(formEntregaDescrBairro)
                    .addComponent(formEntregaDescrCidade)
                    .addComponent(formEntregaDescrCPF)
                    .addComponent(formEntregaFieldComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(formEntregaFieldBairro)
                    .addComponent(formEntregaFieldCidade)
                    .addComponent(formEntregaFieldCPF))
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(formEntregaDescrTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(formEntregaDescrSubTitulo)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(formEntregaVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(formEntregaProsseguir)
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formEntregaDescrTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formEntregaDescrSubTitulo)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaDescrNome)
                    .addComponent(formEntregaDescrCompl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formEntregaFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaDescrCEP)
                    .addComponent(formEntregaDescrBairro))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formEntregaFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaDescrEndereco)
                    .addComponent(formEntregaDescrCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formEntregaFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaDescrNumero)
                    .addComponent(formEntregaDescrCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formEntregaFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formEntregaVoltar)
                    .addComponent(formEntregaProsseguir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFormEntregaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFormEntregaVoltarActionPerformed
        // TODO add your handling code here:
        CarrinhoTela voltar = new CarrinhoTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoFormEntregaVoltarActionPerformed

    private void botaoFormEntregaProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFormEntregaProsseguirActionPerformed
        // TODO add your handling code here:
        GeraBoleto boleto = new GeraBoleto();
        boleto.fazBoleto(formEntregaFieldNome.getText(), formEntregaFieldCPF.getText(), formEntregaFieldEndereco.getText(), formEntregaFieldNumero.getText(), formEntregaFieldComplemento.getText(), formEntregaFieldBairro.getText(), formEntregaFieldCEP.getText(), formEntregaFieldCidade.getText());
        PagamentoTela pagar = new PagamentoTela();
        this.dispose();
        pagar.setVisible(true);
    }//GEN-LAST:event_botaoFormEntregaProsseguirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEnderecoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEnderecoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEnderecoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEnderecoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEnderecoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel formEntregaDescrBairro;
    private javax.swing.JLabel formEntregaDescrCEP;
    private javax.swing.JLabel formEntregaDescrCPF;
    private javax.swing.JLabel formEntregaDescrCidade;
    private javax.swing.JLabel formEntregaDescrCompl;
    private javax.swing.JLabel formEntregaDescrEndereco;
    private javax.swing.JLabel formEntregaDescrNome;
    private javax.swing.JLabel formEntregaDescrNumero;
    private javax.swing.JLabel formEntregaDescrSubTitulo;
    private javax.swing.JLabel formEntregaDescrTitulo;
    private javax.swing.JTextField formEntregaFieldBairro;
    private javax.swing.JTextField formEntregaFieldCEP;
    private javax.swing.JTextField formEntregaFieldCPF;
    private javax.swing.JTextField formEntregaFieldCidade;
    private javax.swing.JTextField formEntregaFieldComplemento;
    private javax.swing.JTextField formEntregaFieldEndereco;
    private javax.swing.JTextField formEntregaFieldNome;
    private javax.swing.JTextField formEntregaFieldNumero;
    private javax.swing.JButton formEntregaProsseguir;
    private javax.swing.JButton formEntregaVoltar;
    // End of variables declaration//GEN-END:variables
}
