/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;

import br.unirio.pcs.suta.GmailAPI;

/**
 *
 * @author Lucas
 */
public class MsgErroLivroTela extends javax.swing.JFrame {

    /**
     * Creates new form MsgErroLivroTela2
     */
    public MsgErroLivroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgErroLivroEnviar = new javax.swing.JButton();
        msgErroLivroVoltar = new javax.swing.JButton();
        msgErroLivroPane = new javax.swing.JScrollPane();
        msgErroLivroTexto = new javax.swing.JTextArea();
        msgErroLivroDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        msgErroLivroEnviar.setText("Enviar mensagem");
        msgErroLivroEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgErroLivroEnviarActionPerformed(evt);
            }
        });

        msgErroLivroVoltar.setText("Voltar para tela principal");
        msgErroLivroVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgErroLivroVoltarActionPerformed(evt);
            }
        });

        msgErroLivroTexto.setColumns(20);
        msgErroLivroTexto.setRows(5);
        msgErroLivroPane.setViewportView(msgErroLivroTexto);

        msgErroLivroDescricao.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        msgErroLivroDescricao.setText("Favor detalhar a experiência com o livro e possíveis melhorias e correções no campo abaixo. ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msgErroLivroDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(msgErroLivroVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(msgErroLivroEnviar))
                            .addComponent(msgErroLivroPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(msgErroLivroDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msgErroLivroPane, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(msgErroLivroEnviar)
                    .addComponent(msgErroLivroVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msgErroLivroEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgErroLivroEnviarActionPerformed
        // TODO add your handling code here:
        GmailAPI mail = new GmailAPI();
        mail.sendMail(msgErroLivroTexto.getText(), "sutapcsobra@gmail.com", "Erro em obra");
        PrincipalTela enviar = new PrincipalTela();
        this.dispose();
        enviar.setVisible(true);
    }//GEN-LAST:event_msgErroLivroEnviarActionPerformed

    private void msgErroLivroVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgErroLivroVoltarActionPerformed
        // TODO add your handling code here:
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_msgErroLivroVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MsgErroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MsgErroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MsgErroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MsgErroLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MsgErroLivroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel msgErroLivroDescricao;
    private javax.swing.JButton msgErroLivroEnviar;
    private javax.swing.JScrollPane msgErroLivroPane;
    private javax.swing.JTextArea msgErroLivroTexto;
    private javax.swing.JButton msgErroLivroVoltar;
    // End of variables declaration//GEN-END:variables
}
