/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;

/**
 *
 * @author Lucas
 */
public class ResumoLivroTela extends javax.swing.JFrame {

    /**
     * Creates new form ResumoLivro
     */
    public ResumoLivroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumoLivroTelajaLeuCheckBox = new javax.swing.JCheckBox();
        resumoLivroTelanotaObra = new javax.swing.JTextField();
        resumoLivroTeladescrNotaOBra = new javax.swing.JLabel();
        resumoLivroTeladescrTitulo = new javax.swing.JLabel();
        resumoLivroTelaPane = new javax.swing.JScrollPane();
        resumoLivroTelaSinopse = new javax.swing.JTextArea();
        resumoLivroTelaVoltar = new javax.swing.JButton();
        resumoLivroTelaAdicionar = new javax.swing.JButton();
        resumoLivroTelaReportErro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resumoLivroTelajaLeuCheckBox.setText("Já Leu?");

        resumoLivroTeladescrNotaOBra.setText("Dê sua nota de 1 a 5:");

        resumoLivroTeladescrTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resumoLivroTeladescrTitulo.setText("Nome Livro");

        resumoLivroTelaSinopse.setColumns(20);
        resumoLivroTelaSinopse.setRows(5);
        resumoLivroTelaPane.setViewportView(resumoLivroTelaSinopse);

        resumoLivroTelaVoltar.setText("Voltar ao catalogo");
        resumoLivroTelaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResumoLivroTelaVoltarActionPerformed(evt);
            }
        });

        resumoLivroTelaAdicionar.setText("Adicionar ao Pedido");
        resumoLivroTelaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResumoLivroTelaAdicionarActionPerformed(evt);
            }
        });

        resumoLivroTelaReportErro.setText("Reportar erro nessa obra");
        resumoLivroTelaReportErro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoResumoLivroTelaReportErroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resumoLivroTeladescrTitulo)
                            .addComponent(resumoLivroTelaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(resumoLivroTelajaLeuCheckBox)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(resumoLivroTelaReportErro)
                                        .addGap(18, 18, 18)
                                        .addComponent(resumoLivroTelaVoltar)))
                                .addGap(18, 18, 18)
                                .addComponent(resumoLivroTelaAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(resumoLivroTeladescrNotaOBra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resumoLivroTelanotaObra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(resumoLivroTeladescrTitulo)
                .addGap(18, 18, 18)
                .addComponent(resumoLivroTelaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resumoLivroTelaAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(resumoLivroTelajaLeuCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resumoLivroTeladescrNotaOBra)
                            .addComponent(resumoLivroTelanotaObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resumoLivroTelaVoltar)
                            .addComponent(resumoLivroTelaReportErro))))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoResumoLivroTelaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResumoLivroTelaAdicionarActionPerformed
        // TODO add your handling code here:
        CarrinhoTela adicionar = new CarrinhoTela();
        this.dispose();
        adicionar.setVisible(true);
    }//GEN-LAST:event_botaoResumoLivroTelaAdicionarActionPerformed

    private void botaoResumoLivroTelaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResumoLivroTelaVoltarActionPerformed
        // TODO add your handling code here:
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoResumoLivroTelaVoltarActionPerformed

    private void botaoResumoLivroTelaReportErroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoResumoLivroTelaReportErroActionPerformed
        MsgErroLivroTela reportar = new MsgErroLivroTela();
        this.dispose();
        reportar.setVisible(true);
    }//GEN-LAST:event_botaoResumoLivroTelaReportErroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResumoLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResumoLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResumoLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResumoLivroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResumoLivroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton resumoLivroTelaAdicionar;
    private javax.swing.JScrollPane resumoLivroTelaPane;
    private javax.swing.JButton resumoLivroTelaReportErro;
    private javax.swing.JTextArea resumoLivroTelaSinopse;
    private javax.swing.JButton resumoLivroTelaVoltar;
    private javax.swing.JLabel resumoLivroTeladescrNotaOBra;
    private javax.swing.JLabel resumoLivroTeladescrTitulo;
    private javax.swing.JCheckBox resumoLivroTelajaLeuCheckBox;
    private javax.swing.JTextField resumoLivroTelanotaObra;
    // End of variables declaration//GEN-END:variables
}
