/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;

/**
 *
 * @author Lucas
 */
public class AlteraCadastroTela extends javax.swing.JFrame {

    /**
     * Creates new form FormEndereco
     */
    public AlteraCadastroTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarCadastroDescrTitulo = new javax.swing.JLabel();
        editarCadastroFieldLogin = new javax.swing.JTextField();
        editarCadastroFieldCPF = new javax.swing.JTextField();
        editarCadastroFieldNome = new javax.swing.JTextField();
        editarCadastroFieldEmail = new javax.swing.JTextField();
        editarCadastroFieldSenha = new javax.swing.JTextField();
        editarCadastroFieldSenhaConfirm = new javax.swing.JTextField();
        editarCadastroFieldDescrLogin = new javax.swing.JLabel();
        editarCadastroFieldDescrSenha = new javax.swing.JLabel();
        editarCadastroFieldDescrCPF = new javax.swing.JLabel();
        editarCadastroFieldDescrConfirmSenha = new javax.swing.JLabel();
        editarCadastroFieldDescrNome = new javax.swing.JLabel();
        editarCadastroFieldDescrEmail = new javax.swing.JLabel();
        editarCadastroVoltar = new javax.swing.JButton();
        editarCadastroAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editarCadastroDescrTitulo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        editarCadastroDescrTitulo.setText("Editar Cadastro");

        editarCadastroFieldDescrLogin.setText("Apelido(Login)");

        editarCadastroFieldDescrSenha.setText("Senha");

        editarCadastroFieldDescrCPF.setText("CPF");

        editarCadastroFieldDescrConfirmSenha.setText("Confirme a senha");

        editarCadastroFieldDescrNome.setText("Nome Completo");

        editarCadastroFieldDescrEmail.setText("Email");

        editarCadastroVoltar.setText("Voltar para tela inicial");
        editarCadastroVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCadastroVoltarActionPerformed(evt);
            }
        });

        editarCadastroAlterar.setText("Fazer Alterações");
        editarCadastroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarCadastroAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editarCadastroFieldDescrLogin)
                        .addComponent(editarCadastroFieldDescrCPF)
                        .addComponent(editarCadastroFieldDescrNome)
                        .addComponent(editarCadastroFieldDescrEmail)
                        .addComponent(editarCadastroFieldCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(editarCadastroFieldEmail)
                        .addComponent(editarCadastroFieldLogin))
                    .addComponent(editarCadastroFieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCadastroVoltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editarCadastroFieldDescrSenha)
                        .addComponent(editarCadastroFieldDescrConfirmSenha)
                        .addComponent(editarCadastroFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                        .addComponent(editarCadastroFieldSenhaConfirm))
                    .addComponent(editarCadastroAlterar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(111, 111, 111))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(338, Short.MAX_VALUE)
                .addComponent(editarCadastroDescrTitulo)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(editarCadastroDescrTitulo)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCadastroFieldDescrLogin)
                    .addComponent(editarCadastroFieldDescrSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCadastroFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCadastroFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCadastroFieldDescrCPF)
                    .addComponent(editarCadastroFieldDescrConfirmSenha))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCadastroFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarCadastroFieldSenhaConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(editarCadastroFieldDescrNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarCadastroFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editarCadastroFieldDescrEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarCadastroFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarCadastroVoltar)
                    .addComponent(editarCadastroAlterar))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarCadastroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCadastroAlterarActionPerformed
        // TODO add your handling code here:
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoEditarCadastroAlterarActionPerformed

    private void botaoEditarCadastroVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarCadastroVoltarActionPerformed
        // TODO add your handling code here:
        PrincipalTela editar = new PrincipalTela();
        this.dispose();
        editar.setVisible(true);
    }//GEN-LAST:event_botaoEditarCadastroVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlteraCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlteraCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlteraCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlteraCadastroTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlteraCadastroTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editarCadastroAlterar;
    private javax.swing.JLabel editarCadastroDescrTitulo;
    private javax.swing.JTextField editarCadastroFieldCPF;
    private javax.swing.JLabel editarCadastroFieldDescrCPF;
    private javax.swing.JLabel editarCadastroFieldDescrConfirmSenha;
    private javax.swing.JLabel editarCadastroFieldDescrEmail;
    private javax.swing.JLabel editarCadastroFieldDescrLogin;
    private javax.swing.JLabel editarCadastroFieldDescrNome;
    private javax.swing.JLabel editarCadastroFieldDescrSenha;
    private javax.swing.JTextField editarCadastroFieldEmail;
    private javax.swing.JTextField editarCadastroFieldLogin;
    private javax.swing.JTextField editarCadastroFieldNome;
    private javax.swing.JTextField editarCadastroFieldSenha;
    private javax.swing.JTextField editarCadastroFieldSenhaConfirm;
    private javax.swing.JButton editarCadastroVoltar;
    // End of variables declaration//GEN-END:variables
}
