/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.unirio.pcs.suta.ui;

/**
 *
 * @author Lucas
 */
public class CarrinhoTela extends javax.swing.JFrame {

    /**
     * Creates new form Carrinho
     */
    public CarrinhoTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        visuPedidoDescricao = new javax.swing.JLabel();
        visuPedidoPane = new javax.swing.JScrollPane();
        visuPedidoTabela = new javax.swing.JTable();
        visuPedidoProsseguir = new javax.swing.JButton();
        visuPedidoCancelar = new javax.swing.JButton();
        visuPedidoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        visuPedidoDescricao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        visuPedidoDescricao.setText("Seu Pedido no momento:");

        visuPedidoTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome Livro", "Preço por unidade", "Quantidade"
            }
        ));
        visuPedidoPane.setViewportView(visuPedidoTabela);

        visuPedidoProsseguir.setText("Prosseguir com pedido");
        visuPedidoProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoProsseguirActionPerformed(evt);
            }
        });

        visuPedidoCancelar.setText("Cancelar pedido");
        visuPedidoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoCancelarActionPerformed(evt);
            }
        });

        visuPedidoVoltar.setText("Voltar ao catalogo");
        visuPedidoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVisuPedidoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(visuPedidoVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visuPedidoCancelar)
                .addGap(65, 65, 65)
                .addComponent(visuPedidoProsseguir)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(visuPedidoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(visuPedidoDescricao)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(visuPedidoDescricao)
                .addGap(38, 38, 38)
                .addComponent(visuPedidoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visuPedidoProsseguir)
                    .addComponent(visuPedidoCancelar)
                    .addComponent(visuPedidoVoltar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVisuPedidoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoCancelarActionPerformed
        // TODO add your handling code here:
        CarrinhoTela cancelar = new CarrinhoTela();
        this.dispose();
        cancelar.setVisible(true);
    }//GEN-LAST:event_botaoVisuPedidoCancelarActionPerformed

    private void botaoVisuPedidoProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoProsseguirActionPerformed
        // TODO add your handling code here:
        FormEnderecoTela prosseguiu = new FormEnderecoTela();
        this.dispose();
        prosseguiu.setVisible(true);
    }//GEN-LAST:event_botaoVisuPedidoProsseguirActionPerformed

    private void botaoVisuPedidoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVisuPedidoVoltarActionPerformed
        // TODO add your handling code here:
        PrincipalTela voltar = new PrincipalTela();
        this.dispose();
        voltar.setVisible(true);
    }//GEN-LAST:event_botaoVisuPedidoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarrinhoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarrinhoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton visuPedidoCancelar;
    private javax.swing.JLabel visuPedidoDescricao;
    private javax.swing.JScrollPane visuPedidoPane;
    private javax.swing.JButton visuPedidoProsseguir;
    private javax.swing.JTable visuPedidoTabela;
    private javax.swing.JButton visuPedidoVoltar;
    // End of variables declaration//GEN-END:variables
}
